# Generated by Django 2.2.4 on 2019-08-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190815_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
