# Generated by Django 2.2.4 on 2019-08-18 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('text', models.TextField(max_length=255, null=True)),
                ('target', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnumber', models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков')),
                ('likedone', models.ManyToManyField(related_name='users_video_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('creator', models.TextField(max_length=30, null=True)),
                ('about', models.TextField(max_length=255, null=True)),
                ('closed', models.TextField(null=True)),
                ('room', models.IntegerField(null=True)),
                ('helper', models.TextField(max_length=30, null=True)),
                ('likes', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Like')),
            ],
        ),
    ]
