# Generated by Django 2.2.4 on 2019-08-18 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likedone',
            field=models.ManyToManyField(null=None, related_name='users_video_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
