# Generated by Django 2.2.4 on 2019-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.IntegerField(null=True),
        ),
    ]
