# Generated by Django 2.2.4 on 2019-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_comment_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('creater', models.TextField(max_length=30, null=True)),
                ('about', models.TextField(max_length=255, null=True)),
                ('closed', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
