# Generated by Django 2.2.4 on 2019-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190817_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='room',
            field=models.IntegerField(null=True),
        ),
    ]
