# Generated by Django 2.2.4 on 2019-08-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_problem_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='helper',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
