# Generated by Django 2.2.4 on 2019-08-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_problem_helper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='creater',
            new_name='creator',
        ),
    ]
