# Generated by Django 2.2.4 on 2019-08-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190817_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='closed',
            field=models.TextField(null=True),
        ),
    ]
